CB-30241 Validate the trust status when the setup-finish is called
Also improve the validate script to only include useful info on stdout/stderr

diff --git a/freeipa/src/main/resources/freeipa-salt/salt/trustsetup/validation/scripts/trust_status_validation.sh.j2 b/freeipa/src/main/resources/freeipa-salt/salt/trustsetup/validation/scripts/trust_status_validation.sh.j2
--- a/freeipa/src/main/resources/freeipa-salt/salt/trustsetup/validation/scripts/trust_status_validation.sh.j2
+++ b/freeipa/src/main/resources/freeipa-salt/salt/trustsetup/validation/scripts/trust_status_validation.sh.j2
@@ -1,5 +1,8 @@
 #!/bin/bash
 
-kdestroy
-echo "$ADMIN_PASSWORD" | kinit admin
+if ! RESULT=$( (kdestroy; echo "$ADMIN_PASSWORD" | kinit admin) 2>&1); then
+  echo "Failed to kinit admin:"
+  echo "$RESULT"
+  exit 1
+fi
 kvno "ldap/${AD_FQDN}@${AD_REALM}"
