CB-7089: Prevent Freeipa backup script parallel runs
This adds locks to the backup scripts so that only one backup
job can run at any one time on a host.

diff --git a/freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_backup b/freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_backup
--- a/freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_backup
+++ b/freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_backup
@@ -1,10 +1,28 @@
 #!/bin/bash
-# Name: freeipa_backup.sh
+# Name: freeipa_backup
 # Description: Backup FreeIPA and Upload backup to provided Cloud Location
 ################################################################
 set -x
 
 CONFIG_FILE=/etc/freeipa_backup.conf
+
+LOCKFILE="/var/lock/`basename $0`"
+LOCKFD=99
+
+# PRIVATE
+_lock()             { flock -$1 $LOCKFD; }
+_no_more_locking()  { _lock u; _lock xn && rm -f $LOCKFILE; }
+_prepare_locking()  { eval "exec $LOCKFD>\"$LOCKFILE\""; trap _no_more_locking EXIT; }
+
+# ON START
+_prepare_locking
+
+# PUBLIC
+exlock_now()        { _lock xn; }  # obtain an exclusive lock immediately or fail
+exlock()            { _lock x; }   # obtain an exclusive lock
+shlock()            { _lock s; }   # obtain a shared lock
+unlock()            { _lock u; }   # drop a lock
+
 
 # Config Defaults
 typeset -A config # init array
@@ -86,7 +104,7 @@ doLog(){
 error_exit()
 {
     doLog "ERROR $1"
-	exit 1
+	  exit 1
 }
 
 remove_local_backups() {
@@ -95,6 +113,8 @@ remove_local_backups() {
 }
 
 doLog "INFO Running ${TYPE} IPA backup."
+
+exlock_now || error_exit "A backup seems to be currently running. Lock file is at ${LOCKFILE}"
 
 set +x
 if [[ -n "${config[http_proxy]}" ]]; then
